#+TITLE:   tools/pandoc
#+DATE:    November 13, 2019
#+SINCE:   v2.0.9
#+STARTUP: inlineimages

* Table of Contents :TOC_3:noexport:
- [[#description][Description]]
  - [[#module-flags][Module Flags]]
  - [[#plugins][Plugins]]
  - [[#hacks][Hacks]]
- [[#prerequisites][Prerequisites]]
- [[#features][Features]]
- [[#configuration][Configuration]]
- [[#troubleshooting][Troubleshooting]]

* Description
This module adds ~pandoc-mode~, an Emacs minor mode for interacting with the
[[https://pandoc.org][~pandoc~]] document converter.

** Module Flags
This module provides no flags.

** Plugins
- [[https://github.com/joostkremers/pandoc-mode][pandoc-mode]]

** Hacks
The included package has not been modified.

* Prerequisites
This module has no prerequisites.

* Features
See [[https://joostkremers.github.io/pandoc-mode/][the documentation]].

* Configuration
See [[https://joostkremers.github.io/pandoc-mode/][the documentation]].

The following code was used for integration with ~doom~:

#+BEGIN_SRC emacs-lisp
(use-package! pandoc-mode
  :config
  (setq pandoc-data-dir (concat doom-cache-dir "pandoc-mode"))
  :hook
  (;; Activate pandoc-mode on top of common text modes.
   (org-mode markdown-mode text-mode)
   ;; Load default settings file `default.pandoc' in `pandoc-data-dir'.
   (pandoc-mode . pandoc-load-default-settings)))
#+END_SRC

* Troubleshooting
The prefix key ~C-c /~ is already used by ~reftex-index-selection-or-word~ in
LaTeX mode. I haven't tried to find a solution to this conflict, because I only
use ~pandoc~ to generate Word files from markdown or org source files.
